/**
 * GraphQL Client Setup
 *
 * Uses graphql-request for simple, lightweight GraphQL queries to the indexer.
 * Types are generated by gql.tada from the indexer's schema.
 */

import { GraphQLClient } from "graphql-request";

/**
 * The indexer GraphQL endpoint URL.
 * Set via NEXT_PUBLIC_INDEXER_URL environment variable.
 */
export const INDEXER_URL =
  process.env.NEXT_PUBLIC_INDEXER_URL ?? "http://localhost:4000/graphql";

/**
 * GraphQL client for making queries to the indexer.
 *
 * This client is configured with:
 * - The indexer URL from environment
 * - Headers to bypass ngrok browser warning (for development)
 *
 * @example
 * ```ts
 * import { graphqlClient } from "@/lib/graphql/client";
 * import { graphql } from "@/lib/graphql/tada";
 *
 * const query = graphql(`
 *   query GetOrganizations {
 *     gainforest {
 *       organization {
 *         infos {
 *           records {
 *             meta { did }
 *             displayName
 *           }
 *         }
 *       }
 *     }
 *   }
 * `);
 *
 * const data = await graphqlClient.request(query);
 * ```
 */
export const graphqlClient = new GraphQLClient(INDEXER_URL, {
  headers: {
    // Bypass ngrok browser warning page in development
    "ngrok-skip-browser-warning": "true",
  },
});

/**
 * Create a GraphQL client with custom headers (e.g., for authenticated requests).
 */
export function createGraphQLClient(headers?: Record<string, string>) {
  return new GraphQLClient(INDEXER_URL, {
    headers: {
      "ngrok-skip-browser-warning": "true",
      ...headers,
    },
  });
}
