/**
 * THIS FILE IS AUTO-GENERATED by GENERATED/scripts/generate-collections.ts
 *
 * DO NOT EDIT BY HAND.
 *
 * Re-generate with:  bun run gen:indexer   (from monorepo root)
 * (or:               bun run codegen)
 *
 * To exclude a collection from indexing, add its NSID to
 * EXCLUDED_COLLECTIONS in GENERATED/scripts/generate-collections.ts.
 */

// ============================================================
// INDEXED COLLECTIONS
// ============================================================

export const INDEXED_COLLECTIONS = [
  "app.certified.actor.profile",
  "app.gainforest.dwc.event",
  "app.gainforest.dwc.measurement",
  "app.gainforest.dwc.occurrence",
  "app.gainforest.evaluator.evaluation",
  "app.gainforest.evaluator.service",
  "app.gainforest.evaluator.subscription",
  "app.gainforest.organization.defaultSite",
  "app.gainforest.organization.info",
  "app.gainforest.organization.layer",
  "app.gainforest.organization.observations.dendogram",
  "app.gainforest.organization.observations.fauna",
  "app.gainforest.organization.observations.flora",
  "app.gainforest.organization.observations.measuredTreesCluster",
  "app.gainforest.organization.predictions.fauna",
  "app.gainforest.organization.predictions.flora",
  "app.gainforest.organization.recordings.audio",
  "org.hypercerts.acknowledgement",
  "org.hypercerts.claim.activity",
  "org.hypercerts.claim.attachment",
  "org.hypercerts.claim.collection",
  "org.hypercerts.claim.contributionDetails",
  "org.hypercerts.claim.contributorInformation",
  "org.hypercerts.claim.evaluation",
  "org.hypercerts.claim.measurement",
  "org.hypercerts.claim.rights",
  "org.hypercerts.funding.receipt",
  "org.hypercerts.helper.workScopeTag",
  "org.impactindexer.link.attestation",
  "org.impactindexer.review.comment",
  "org.impactindexer.review.like",
] as const;

export type IndexedCollection = (typeof INDEXED_COLLECTIONS)[number];

/** O(1) Set for hot-path filtering. */
export const INDEXED_COLLECTIONS_SET = new Set<string>(INDEXED_COLLECTIONS);

/** Type guard — narrows a string to IndexedCollection. */
export function isIndexedCollection(
  collection: string
): collection is IndexedCollection {
  return INDEXED_COLLECTIONS_SET.has(collection);
}

// ============================================================
// COLLECTION METADATA
// ============================================================

/**
 * Key type used by each collection.
 *   "tid"          — TID key (most records)
 *   "literal:self" — singleton record per DID (e.g. profile, service)
 *   "any"          — unrestricted key
 */
export type RecordKeyType = "tid" | "literal:self" | "any";

export const COLLECTION_KEY_TYPE: Record<IndexedCollection, RecordKeyType> = {
  "app.certified.actor.profile":                             "literal:self",
  "app.gainforest.dwc.event":                                "tid",
  "app.gainforest.dwc.measurement":                          "tid",
  "app.gainforest.dwc.occurrence":                           "tid",
  "app.gainforest.evaluator.evaluation":                     "tid",
  "app.gainforest.evaluator.service":                        "literal:self",
  "app.gainforest.evaluator.subscription":                   "tid",
  "app.gainforest.organization.defaultSite":                 "literal:self",
  "app.gainforest.organization.info":                        "literal:self",
  "app.gainforest.organization.layer":                       "tid",
  "app.gainforest.organization.observations.dendogram":      "literal:self",
  "app.gainforest.organization.observations.fauna":          "tid",
  "app.gainforest.organization.observations.flora":          "tid",
  "app.gainforest.organization.observations.measuredTreesCluster":"tid",
  "app.gainforest.organization.predictions.fauna":           "tid",
  "app.gainforest.organization.predictions.flora":           "tid",
  "app.gainforest.organization.recordings.audio":            "tid",
  "org.hypercerts.acknowledgement":                          "tid",
  "org.hypercerts.claim.activity":                           "any",
  "org.hypercerts.claim.attachment":                         "tid",
  "org.hypercerts.claim.collection":                         "tid",
  "org.hypercerts.claim.contributionDetails":                "tid",
  "org.hypercerts.claim.contributorInformation":             "tid",
  "org.hypercerts.claim.evaluation":                         "tid",
  "org.hypercerts.claim.measurement":                        "tid",
  "org.hypercerts.claim.rights":                             "tid",
  "org.hypercerts.funding.receipt":                          "tid",
  "org.hypercerts.helper.workScopeTag":                      "tid",
  "org.impactindexer.link.attestation":                      "tid",
  "org.impactindexer.review.comment":                        "tid",
  "org.impactindexer.review.like":                           "tid",
};
