/**
 * THIS FILE IS AUTO-GENERATED by GENERATED/scripts/generate-collections.ts
 *
 * DO NOT EDIT BY HAND.
 *
 * Re-generate with:  bun run gen:indexer   (from monorepo root)
 * (or:               bun run codegen)
 *
 * To exclude a collection from indexing, add its NSID to
 * EXCLUDED_COLLECTIONS in GENERATED/scripts/generate-collections.ts.
 */

/**
 * Record validation using \@atproto/lex generated schemas.
 *
 * Each generated schema exposes `$safeValidate(data)` which:
 *   - Validates the record against the full lexicon definition
 *     (grapheme limits, required fields, enum values, formats, etc.)
 *   - Returns { success: true, value } or { success: false, error }
 *   - Does NOT apply defaults or coerce types (unlike $safeParse)
 */

import * as generated from "@/generated/index.ts";
import type { IndexedCollection } from "./collections.ts";

// ============================================================
// SCHEMA REGISTRY
// Maps every indexed collection NSID → its generated schema object.
// ============================================================

type LexSchema = {
  $safeValidate: (data: unknown) => { success: boolean; error?: unknown };
};

const SCHEMA_REGISTRY: Record<IndexedCollection, LexSchema> = {
  "app.certified.actor.organization":                      generated.app.certified.actor.organization,
  "app.certified.actor.profile":                           generated.app.certified.actor.profile,
  "app.certified.badge.award":                             generated.app.certified.badge.award,
  "app.certified.badge.definition":                        generated.app.certified.badge.definition,
  "app.certified.badge.response":                          generated.app.certified.badge.response,
  "app.certified.location":                                generated.app.certified.location,
  "app.gainforest.dwc.event":                              generated.app.gainforest.dwc.event,
  "app.gainforest.dwc.measurement":                        generated.app.gainforest.dwc.measurement,
  "app.gainforest.dwc.occurrence":                         generated.app.gainforest.dwc.occurrence,
  "app.gainforest.evaluator.evaluation":                   generated.app.gainforest.evaluator.evaluation,
  "app.gainforest.evaluator.service":                      generated.app.gainforest.evaluator.service,
  "app.gainforest.evaluator.subscription":                 generated.app.gainforest.evaluator.subscription,
  "app.gainforest.organization.defaultSite":               generated.app.gainforest.organization.defaultSite,
  "app.gainforest.organization.info":                      generated.app.gainforest.organization.info,
  "app.gainforest.organization.layer":                     generated.app.gainforest.organization.layer,
  "app.gainforest.organization.observations.dendogram":    generated.app.gainforest.organization.observations.dendogram,
  "app.gainforest.organization.observations.fauna":        generated.app.gainforest.organization.observations.fauna,
  "app.gainforest.organization.observations.flora":        generated.app.gainforest.organization.observations.flora,
  "app.gainforest.organization.observations.measuredTreesCluster":generated.app.gainforest.organization.observations.measuredTreesCluster,
  "app.gainforest.organization.predictions.fauna":         generated.app.gainforest.organization.predictions.fauna,
  "app.gainforest.organization.predictions.flora":         generated.app.gainforest.organization.predictions.flora,
  "app.gainforest.organization.recordings.audio":          generated.app.gainforest.organization.recordings.audio,
  "org.hyperboards.board":                                 generated.org.hyperboards.board,
  "org.hyperboards.displayProfile":                        generated.org.hyperboards.displayProfile,
  "org.hypercerts.claim.activity":                         generated.org.hypercerts.claim.activity,
  "org.hypercerts.claim.contribution":                     generated.org.hypercerts.claim.contribution,
  "org.hypercerts.claim.contributorInformation":           generated.org.hypercerts.claim.contributorInformation,
  "org.hypercerts.claim.rights":                           generated.org.hypercerts.claim.rights,
  "org.hypercerts.collection":                             generated.org.hypercerts.collection,
  "org.hypercerts.context.acknowledgement":                generated.org.hypercerts.context.acknowledgement,
  "org.hypercerts.context.attachment":                     generated.org.hypercerts.context.attachment,
  "org.hypercerts.context.evaluation":                     generated.org.hypercerts.context.evaluation,
  "org.hypercerts.context.measurement":                    generated.org.hypercerts.context.measurement,
  "org.hypercerts.funding.receipt":                        generated.org.hypercerts.funding.receipt,
  "org.hypercerts.workscope.tag":                          generated.org.hypercerts.workscope.tag,
  "org.impactindexer.link.attestation":                    generated.org.impactindexer.link.attestation,
  "org.impactindexer.review.comment":                      generated.org.impactindexer.review.comment,
  "org.impactindexer.review.like":                         generated.org.impactindexer.review.like,
};

// ============================================================
// PUBLIC API
// ============================================================

export type ValidationResult =
  | { ok: true }
  | { ok: false; error: string };

/**
 * Validate a raw record against its lexicon schema.
 *
 * @param collection - The lexicon collection NSID
 * @param record     - The raw record object from Tap
 */
export function validateRecord(
  collection: string,
  record: unknown
): ValidationResult {
  const schema = SCHEMA_REGISTRY[collection as IndexedCollection];

  // Should not happen — every indexed collection has a schema.
  // Guard retained so a bug here never silently crashes the indexer.
  if (!schema) return { ok: true };

  const result = schema.$safeValidate(record);
  if (result.success) return { ok: true };
  return { ok: false, error: formatError(result.error) };
}

// ============================================================
// HELPERS
// ============================================================

function formatError(error: unknown): string {
  if (error instanceof Error) return error.message;
  if (typeof error === "string") return error;
  try { return JSON.stringify(error); } catch { return String(error); }
}
